apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: gribkov-as-ikbo-16-22
spec:
  containers:
  - name: cpu-demo-ctr
    image: polinux/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    command: ["stress"]
    args:
    - --cpu
    - "2"