services:
  postgres:
    image: postgres:15-alpine
    container_name: mirea-postgres
    environment:
      POSTGRES_DB: mirea_db
      POSTGRES_USER: mirea_user
      POSTGRES_PASSWORD: mirea_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mirea-network

  mirea-app:
    build: .
    container_name: mirea-spring-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mirea_db
      DB_USERNAME: mirea_user
      DB_PASSWORD: mirea_password
    depends_on:
      - postgres
    networks:
      - mirea-network

volumes:
  postgres_data:

networks:
  mirea-network:
    driver: bridge