replicaCount: 1

image:
  repository: web-client
  pullPolicy: Never
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
