apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  db.password: {{ .Values.secrets.dbPassword | quote }}
  redis.password: {{ .Values.secrets.redisPassword | quote }}
  jwt.secret: {{ .Values.secrets.jwtSecret | quote }}

